# Generated by Django 4.2.8 on 2023-12-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
