# Generated by Django 4.2.8 on 2023-12-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_service', '0002_alter_order_order_number_alter_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
